//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abaca
    {
        public int idTransaksi { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string vendorCardNo { get; set; }
        public string vendorName { get; set; }
        public string jobId { get; set; }
        public Nullable<long> totalAmount { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
    }
}
