//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalPembagianSaldo
    {
        public int IdTransaksi { get; set; }
        public System.DateTime Tanggal { get; set; }
        public string PktSumber { get; set; }
        public string PktTujuan { get; set; }
        public string JenisTransaksi { get; set; }
        public string JenisUang { get; set; }
        public long D100 { get; set; }
        public long D50 { get; set; }
    }
}
