//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalView
    {
        public int idApproval { get; set; }
        public System.DateTime tanggal { get; set; }
        public string kodePkt { get; set; }
        public string inputOpr { get; set; }
        public string inputSpv { get; set; }
        public string inputNoTxn { get; set; }
        public string validasiOpr { get; set; }
        public string validasiSpv { get; set; }
        public string validasiNoTxn { get; set; }
        public string koordinator { get; set; }
        public string kanwil { get; set; }
        public int idDetailApproval { get; set; }
        public Nullable<System.DateTime> Expr1 { get; set; }
        public Nullable<long> saldoAwal20 { get; set; }
        public Nullable<long> saldoAwal50 { get; set; }
        public Nullable<long> saldoAwal100 { get; set; }
        public Nullable<long> sislokCRM20 { get; set; }
        public Nullable<long> sislokCRM50 { get; set; }
        public Nullable<long> sislokCRM100 { get; set; }
        public Nullable<long> sislokCDM20 { get; set; }
        public Nullable<long> sislokCDM50 { get; set; }
        public Nullable<long> sislokCDM100 { get; set; }
        public Nullable<long> sislokATM20 { get; set; }
        public Nullable<long> sislokATM100 { get; set; }
        public Nullable<long> sislokATM50 { get; set; }
        public Nullable<long> isiATM20 { get; set; }
        public Nullable<long> isiATM100 { get; set; }
        public Nullable<long> isiATM50 { get; set; }
        public Nullable<long> isiCRM20 { get; set; }
        public Nullable<long> isiCRM50 { get; set; }
        public Nullable<long> bon20 { get; set; }
        public Nullable<long> isiCRM100 { get; set; }
        public Nullable<long> bon50 { get; set; }
        public Nullable<long> bon100 { get; set; }
        public Nullable<long> adhoc20 { get; set; }
        public Nullable<long> adhoc50 { get; set; }
        public Nullable<long> adhoc100 { get; set; }
        public Nullable<long> setor20 { get; set; }
        public Nullable<long> setor50 { get; set; }
        public Nullable<long> setor100 { get; set; }
        public Nullable<long> setorAdhoc100 { get; set; }
        public Nullable<long> setorAdhoc50 { get; set; }
        public Nullable<long> setorAdhoc20 { get; set; }
        public System.DateTime tanggalApproval { get; set; }
    }
}
