//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeritaAcara
    {
        public int idBA { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string kodeCabang { get; set; }
        public string noBeritaAcara { get; set; }
        public Nullable<long> d100k { get; set; }
        public Nullable<long> d50k { get; set; }
        public Nullable<long> d20k { get; set; }
        public Nullable<long> d10k { get; set; }
        public Nullable<long> d5k { get; set; }
        public Nullable<long> d2k { get; set; }
        public Nullable<long> d1k { get; set; }
        public Nullable<long> nominal { get; set; }
        public string jenisIsi { get; set; }
        public Nullable<System.DateTime> tanggalSetor { get; set; }
        public string noTxn { get; set; }
        public string kodePkt { get; set; }
    }
}
