//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyStock
    {
        public int idTransaksi { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string kodePkt { get; set; }
        public string in_out { get; set; }
        public string jenisTransaksi { get; set; }
        public string kode { get; set; }
        public string nama { get; set; }
        public string keterangan { get; set; }
        public Nullable<long> BN100K { get; set; }
        public Nullable<long> BN50K { get; set; }
        public Nullable<long> BN20K { get; set; }
        public Nullable<long> BN10K { get; set; }
        public Nullable<long> BN5K { get; set; }
        public Nullable<long> BN2K { get; set; }
        public Nullable<long> BN1K { get; set; }
        public Nullable<long> BN500 { get; set; }
        public Nullable<long> BN100 { get; set; }
        public Nullable<long> CN1K { get; set; }
        public Nullable<long> CN500 { get; set; }
        public Nullable<long> CN200 { get; set; }
        public Nullable<long> CN100 { get; set; }
        public Nullable<long> CN50 { get; set; }
        public Nullable<long> CN25 { get; set; }
    }
}
