//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryLainnya
    {
        public int idTransaksi { get; set; }
        public string keterangan { get; set; }
        public Nullable<long> bn100000 { get; set; }
        public Nullable<long> bn50000 { get; set; }
        public Nullable<long> bn20000 { get; set; }
        public Nullable<long> bn10000 { get; set; }
        public Nullable<long> bn5000 { get; set; }
        public Nullable<long> bn2000 { get; set; }
        public Nullable<long> bn1000 { get; set; }
        public Nullable<long> bn500 { get; set; }
        public Nullable<long> bn200 { get; set; }
        public Nullable<long> bn100 { get; set; }
        public Nullable<long> c1000 { get; set; }
        public Nullable<long> c500 { get; set; }
        public Nullable<long> c200 { get; set; }
        public Nullable<long> c100 { get; set; }
        public Nullable<long> c50 { get; set; }
        public Nullable<long> c25 { get; set; }
        public string kodePkt { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
    }
}
