//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailApproval
    {
        public int idDetailApproval { get; set; }
        public int idApproval { get; set; }
        public Nullable<long> saldoAwal20 { get; set; }
        public Nullable<long> saldoAwal50 { get; set; }
        public Nullable<long> saldoAwal100 { get; set; }
        public Nullable<long> sislokCRM20 { get; set; }
        public Nullable<long> sislokCRM50 { get; set; }
        public Nullable<long> sislokCRM100 { get; set; }
        public Nullable<long> sislokCDM20 { get; set; }
        public Nullable<long> sislokCDM50 { get; set; }
        public Nullable<long> sislokCDM100 { get; set; }
        public Nullable<long> isiATM20 { get; set; }
        public Nullable<long> isiATM50 { get; set; }
        public Nullable<long> isiATM100 { get; set; }
        public Nullable<long> isiCRM20 { get; set; }
        public Nullable<long> isiCRM50 { get; set; }
        public Nullable<long> isiCRM100 { get; set; }
        public Nullable<long> bon20 { get; set; }
        public Nullable<long> bon50 { get; set; }
        public Nullable<long> bon100 { get; set; }
        public Nullable<long> adhoc20 { get; set; }
        public Nullable<long> adhoc50 { get; set; }
        public Nullable<long> adhoc100 { get; set; }
        public Nullable<long> setor20 { get; set; }
        public Nullable<long> setor50 { get; set; }
        public Nullable<long> setor100 { get; set; }
    }
}
