//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastDetail
    {
        public int idForecast { get; set; }
        public int idForecastDetail { get; set; }
        public Nullable<long> inCabang100 { get; set; }
        public Nullable<long> inCabang50 { get; set; }
        public Nullable<long> inRetail100 { get; set; }
        public Nullable<long> inRetail50 { get; set; }
        public Nullable<long> outATM100 { get; set; }
        public Nullable<long> outATM50 { get; set; }
        public Nullable<long> outCabang100 { get; set; }
        public Nullable<long> outCabang50 { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
    }
}
