//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class HargaLayanan
    {
        public string jenisLayanan { get; set; }
        public string stc_cos { get; set; }
        public Nullable<long> hargaRing1 { get; set; }
        public Nullable<long> hargaRing2 { get; set; }
        public Nullable<long> hargaRing3 { get; set; }
        public Nullable<long> hargaRing4 { get; set; }
        public Nullable<long> hargaRing5 { get; set; }
    }
}
