//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaporanPermintaanAdhoc
    {
        public int idLaporan { get; set; }
        public string kodePkt { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<long> C100 { get; set; }
        public Nullable<long> C50 { get; set; }
        public Nullable<long> C20 { get; set; }
    }
}
