//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nasabah
    {
        public string kodeNasabah { get; set; }
        public string fasilitasLayanan { get; set; }
        public string metodeLayanan { get; set; }
        public string kodeCabang { get; set; }
        public string kodePktCabang { get; set; }
        public string ring { get; set; }
        public string NomorRekening { get; set; }
        public string GroupNasabah { get; set; }
        public string namaNasabah { get; set; }
        public string segmentasiNasabah { get; set; }
        public string sentralisasi { get; set; }
        public string subsidi { get; set; }
        public Nullable<double> persentaseSubsidi { get; set; }
        public Nullable<int> kuota { get; set; }
    }
}
