//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTracking
    {
        public int Id { get; set; }
        public string kodePkt { get; set; }
        public string kodeCabang { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<long> nominalDispute { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string reference_master { get; set; }
        public string sched_id { get; set; }
        public string actn_id { get; set; }
        public string state_blog { get; set; }
    }
}
