//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RekapSelisihAmbilSetor
    {
        public int Id { get; set; }
        public string kodePenerimaDana { get; set; }
        public string kodeSumberDana { get; set; }
        public Nullable<long> lebih { get; set; }
        public Nullable<long> kurang { get; set; }
        public Nullable<long> palsu { get; set; }
        public Nullable<long> mutilasi { get; set; }
        public Nullable<long> total { get; set; }
        public string noTxn { get; set; }
        public Nullable<System.DateTime> tanggalTransaksi { get; set; }
        public Nullable<System.DateTime> tanggalTemu { get; set; }
        public string noBA { get; set; }
        public string keterangan { get; set; }
        public string transaksi { get; set; }
    }
}
