//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RekonSaldoInputanUser
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string in_out { get; set; }
        public string jenis { get; set; }
        public Nullable<long> value { get; set; }
        public string kodePkt { get; set; }
        public string keterangan { get; set; }
    }
}
