//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoMesin
    {
        public System.DateTime tanggal { get; set; }
        public string wsid { get; set; }
        public string kodeLaporan { get; set; }
        public string cabang { get; set; }
        public Nullable<long> standarPengisianCartridge { get; set; }
        public Nullable<long> totalPengeluaran { get; set; }
        public Nullable<long> totalPemasukan { get; set; }
        public Nullable<long> saldoH { get; set; }
        public Nullable<long> saldoHariSebelumnya { get; set; }
        public string jenisMesin { get; set; }
    }
}
