//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class saveBeeHive
    {
        public int id { get; set; }
        public string kodePerusahaan { get; set; }
        public Nullable<long> totalNominal { get; set; }
        public string jenisFile { get; set; }
        public Nullable<System.DateTime> tanggalTransaksi { get; set; }
        public Nullable<System.DateTime> tanggalKredit { get; set; }
        public string namaFile { get; set; }
    }
}
