//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveRekap
    {
        public int id { get; set; }
        public string kodePkt { get; set; }
        public Nullable<long> orderTracking { get; set; }
        public Nullable<long> rekapSelesai { get; set; }
        public Nullable<long> rekapBelumSelesai { get; set; }
        public Nullable<long> totalRekap { get; set; }
        public string keterangan { get; set; }
        public string komentar { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
    }
}
