//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class saveMc
    {
        public int id { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<System.DateTime> realDate { get; set; }
        public string customerCode { get; set; }
        public Nullable<long> amountTotal { get; set; }
        public Nullable<long> d100k { get; set; }
        public Nullable<long> d50k { get; set; }
        public Nullable<long> d20k { get; set; }
        public Nullable<long> d10k { get; set; }
        public Nullable<long> d5k { get; set; }
        public Nullable<long> d2k { get; set; }
        public Nullable<long> d1k { get; set; }
        public Nullable<long> amountCoin { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    }
}
