//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokPosisi
    {
        public int id { get; set; }
        public Nullable<long> unprocessed { get; set; }
        public Nullable<long> newBaru { get; set; }
        public Nullable<long> newLama { get; set; }
        public Nullable<long> fitBaru { get; set; }
        public Nullable<long> fitNKRI { get; set; }
        public Nullable<long> fitLama { get; set; }
        public Nullable<long> passThrough { get; set; }
        public Nullable<long> unfitBaru { get; set; }
        public Nullable<long> unfitNKRI { get; set; }
        public Nullable<long> unfitLama { get; set; }
        public Nullable<long> RRMBaru { get; set; }
        public Nullable<long> RRMNKRI { get; set; }
        public Nullable<long> RRMLama { get; set; }
        public Nullable<long> RupiahRusakMayor { get; set; }
        public Nullable<long> cekLaporan { get; set; }
        public string jenis { get; set; }
        public string denom { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string namaPkt { get; set; }
        public Nullable<long> inCabang { get; set; }
        public Nullable<long> inRetail { get; set; }
        public Nullable<long> outCabang { get; set; }
        public Nullable<long> openBalance { get; set; }
        public Nullable<long> inBI { get; set; }
        public Nullable<long> inTUKAB { get; set; }
        public Nullable<long> inOtherCPC { get; set; }
        public Nullable<long> inTukaran { get; set; }
        public Nullable<long> outRetail { get; set; }
        public Nullable<long> outBIULE { get; set; }
        public Nullable<long> outBIUTLE { get; set; }
        public Nullable<long> outTUKAB { get; set; }
        public Nullable<long> outOtherCPC { get; set; }
        public Nullable<long> outVaultATM { get; set; }
        public Nullable<long> outTukaran { get; set; }
        public Nullable<long> inVaultATM { get; set; }
    }
}
