//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectBCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultOrderBlogHistory
    {
        public int Id { get; set; }
        public string vaultId { get; set; }
        public string cashPoint { get; set; }
        public string action { get; set; }
        public string status { get; set; }
        public string confNum { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<System.DateTime> timeStamp { get; set; }
        public string taskId { get; set; }
        public string blogMessage { get; set; }
        public string userName { get; set; }
        public Nullable<long> currencyAmmount { get; set; }
    }
}
